version: '3'
services:
  api:
    build: .
    ports:
     - "8080:8080"
    networks:
      - compose_network
    depends_on:
      - kelon
      - mysql
      - redis
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: ''
      ACCESS_SECRET: '98hbun98hsdfsdwesdfs'
      REFRESH_SECRET: '786dfdbjhsbsdfsdfsdf'
      MYSQL_HOST: 'mysql'
      MYSQL_DATABASE: 'myblog'
      MYSQL_USER: 'You'
      MYSQL_PASSWORD: 'SuperSecure'
      ENFORCER_ENPOINT: http://kelon:8181/v1/data
      PORT: '8080'
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - compose_network

  kelon:
    image: kelonio/kelon
    restart: always
    networks:
      - compose_network
    ports:
      - '8181:8181'
      - '9191:9191'
    volumes:
      - ./kelon/config/:/conf
      - ./kelon/call-operands/:/call-operands
      - ./kelon/policies/:/policies
    environment:
      - DATASTORE_CONF=/conf/datastore.yml
      - API_CONF=/conf/api.yml
      - OPA_CONF=/conf/opa.yml
      - REGO_DIR=/policies
      - CONFIG_WATCHER_PATH=/policies
      # - LOG_LEVEL=DEBUG
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'myblog'
      MYSQL_USER: 'You'
      MYSQL_PASSWORD: 'SuperSecure'
      MYSQL_ROOT_PASSWORD: 'root-beats-everything'
    networks:
      - compose_network
    ports:
      - '3306:3306'
    volumes:
      - ./init/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql

networks:
  compose_network:
    driver: bridge